# Return — Simple Return และ Log Return

Portfolio Management Toolkit Notes · เริ่มจากคำถามว่า “เงินลงทุนของเราโตขึ้นเท่าไร?”

ซื้อสินทรัพย์ 80 บาท ขาย 100 บาท ได้กำไร 20 บาท แต่ถ้าซื้ออีกสินทรัพย์ที่ 400 บาทแล้วขาย 420 บาท กำไร 20 บาทเท่ากันไม่ได้หมายถึงผลการลงทุนเท่ากัน เพราะเงินที่ใช้เริ่มต้นต่างกัน ตัวแรกให้ผลตอบแทน 25% ส่วนตัวที่สองให้ 5%

[Return หรือผลตอบแทน](https://nutdnuy.github.io/quantitative-finance-notes/glossary.html#return) ทำให้เราเปรียบเทียบการเปลี่ยนแปลงของเงินลงทุนในรูปสัดส่วนได้ ก่อนนำไปวัดความเสี่ยงหรือจัดพอร์ต ต้องตกลงกันก่อนว่าใช้ผลตอบแทนแบบไหน วัดนานเท่าไร และนับเงินที่ได้รับระหว่างถืออย่างไร

บทนี้เป็นพื้นฐานของชุด **Portfolio Management Toolkit Notes** อ่านได้โดยไม่ต้องมีความรู้เรื่องอนุพันธ์ ใช้ทั้งสามแหล่งที่ระบุท้ายบทเป็นจุดตั้งต้น แล้วตรวจสูตรและสร้างตัวอย่างสมมติขึ้นใหม่ ตัวเลขไม่ใช่ข้อมูลตลาดหรือผล Backtest ของกลยุทธ์ใด

## 1. Simple return: ได้หรือเสียเท่าไรเมื่อเทียบกับเงินต้น

ให้ $P_{t-1}$ เป็นราคาต้นช่วง และ $P_t$ เป็นราคาปลายช่วง หน่วยเป็นบาทต่อหุ้นเหมือนกัน เมื่อไม่มีปันผล [Simple return](https://nutdnuy.github.io/quantitative-finance-notes/glossary.html#return) คือ

$$
R_t=\frac{P_t-P_{t-1}}{P_{t-1}}=\frac{P_t}{P_{t-1}}-1.
$$

ตัว $t$ นับช่วงเวลาที่เลือก อาจเป็นวัน เดือน หรือปี ผลตอบแทนจึงไม่ได้หมายถึงผลตอบแทนรายวันเสมอไป และ 5% ต่อเดือนย่อมเทียบตรง ๆ กับ 5% ต่อปีไม่ได้

ราคา 80 → 100 ให้ $R=0.25$ หรือ 25% ตัวเลข 0.25 เป็นทศนิยมที่ใช้คำนวณ ส่วน 25% เป็นรูปแสดงผล ห้ามใส่ 25 ลงในสูตรที่ต้องการ 0.25

อีกค่าที่ใช้บ่อยคือ **Gross return** หรือ $G_t=1+R_t$ ซึ่งเป็นตัวคูณเงินลงทุน ตัวอย่างนี้ได้ $G=1.25$: เงินต้น 1 บาทกลายเป็น 1.25 บาท Gross return 1.25 จึงไม่ใช่กำไร 125%

ถ้ารับปันผล $D_t$ ต่อหุ้นเมื่อสิ้นช่วง ผลตอบแทนรวมก่อนภาษีและค่าใช้จ่ายคือ

$$
R_t^{\mathrm{total}}=\frac{P_t+D_t-P_{t-1}}{P_{t-1}}.
$$

เช่น ซื้อ 80 บาท สิ้นช่วงเหลือ 79 บาท แต่รับปันผล 3 บาท ผลตอบแทนจากราคาเท่ากับ −1.25% ขณะที่ผลตอบแทนรวมเท่ากับ 2.5% หากใช้ราคาหรือดัชนีที่ปรับปันผลไว้แล้ว ต้องตรวจวิธีปรับก่อนเพื่อไม่บวกปันผลซ้ำ การเชื่อมผลตอบแทนรวมหลายช่วงด้วยการคูณสะท้อนการนำเงินที่ได้รับกลับไปลงทุนตามวิธีสร้างชุดข้อมูลนั้น

## 2. หลายช่วงเวลา: ทำไมบวกเปอร์เซ็นต์ตรง ๆ ไม่ได้

สมมติลงทุน 1,000 บาท เดือนแรกได้ +20% เดือนที่สองได้ −20% โดยไม่มีฝากถอน ปันผล หรือค่าใช้จ่าย

| เวลา | ผลตอบแทนในเดือนนั้น | มูลค่าปลายเดือน |
|---|---:|---:|
| เริ่มต้น | — | 1,000 บาท |
| เดือน 1 | +20% | 1,200 บาท |
| เดือน 2 | −20% | 960 บาท |

กำไรเดือนแรกเท่ากับ 200 บาท แต่ขาดทุนเดือนที่สองเท่ากับ 240 บาท เพราะคิดจากฐานเงิน 1,200 บาท ผลตอบแทนรวมจึงเป็น −4% แม้ผลบวกของเปอร์เซ็นต์จะเป็นศูนย์

สูตรเชื่อม $T$ ช่วงเวลาที่ต่อกันคือ

$$
1+R_{0:T}=\prod_{t=1}^{T}(1+R_t),
\qquad R_{0:T}=\prod_{t=1}^{T}(1+R_t)-1.
$$

เครื่องหมาย $\prod$ หมายถึงนำทุกพจน์มาคูณกัน สำหรับสองช่วง

$$
R_{0:2}=R_1+R_2+R_1R_2.
$$

การบวกเพียง $R_1+R_2$ ทำพจน์ทบต้นหายไป ในตัวอย่างนี้ $0.20\times(-0.20)=-0.04$ พอดี **Simple return ใช้วัดผลตอบแทนสะสมได้อย่างถูกต้อง เพียงต้องเชื่อมด้วยการคูณ gross returns**

## 3. Log return: เปลี่ยนการคูณให้เป็นการบวก

[Log return](https://nutdnuy.github.io/quantitative-finance-notes/glossary.html#log-return) ใช้ลอการิทึมธรรมชาติ $\ln$ ซึ่งมีฐาน $e$ ไม่ใช่ log ฐาน 10

$$
r_t=\ln\left(\frac{P_t}{P_{t-1}}\right)=\ln(1+R_t),
\qquad R_t=e^{r_t}-1.
$$

ทั้งสองรูปให้ข้อมูลการเปลี่ยนแปลงเดียวกันและแปลงกลับกันได้แน่นอนเมื่อ gross return เป็นบวก Log return ไม่ใช่ค่าประมาณของ simple return; สิ่งที่เป็นการประมาณคือการถือว่า $r_t\approx R_t$ เมื่อผลตอบแทนมีขนาดเล็ก

เพราะ $\ln(ab)=\ln a+\ln b$ เราจึงได้

$$
r_{0:T}=\sum_{t=1}^{T}r_t,
\qquad R_{0:T}=\exp\left(\sum_{t=1}^{T}r_t\right)-1.
$$

สำหรับเงิน 1,000 → 1,200 → 960 บาท

| ช่วง | Simple return | Log return (ทศนิยม) |
|---|---:|---:|
| เดือน 1 | +20% | 0.182322 |
| เดือน 2 | −20% | −0.223144 |
| รวมสองเดือน | −4% | −0.040822 |

เมื่อแปลงกลับ $e^{-0.04082199}-1=-0.04$ ได้ −4% เท่ากับวิธีทบต้น อย่ารายงาน log return −0.040822 ว่าขาดทุนเงินจริง 4.0822% หากคูณ log return ด้วย 100 เพื่อแสดงผล ต้องติดป้ายว่าเป็น **log return × 100** ให้ชัด

ชื่อ continuously compounded return มาจากการเขียนตัวคูณการเติบโตเป็น $e^r$ ไม่ได้แปลว่าข้อมูลต้องมีทุกขณะ หรือว่าราคาต้องเคลื่อนที่ต่อเนื่อง เราคำนวณ log return จากราคาที่สังเกตห่างกันหนึ่งเดือนก็ได้

## 4. ลงแล้วกลับขึ้น: ฐานเงินเปลี่ยน แต่เศรษฐศาสตร์ไม่เปลี่ยน

ประเด็นสำคัญจากเอกสารของ Motty Shai คือความไม่สมมาตรของ simple return เมื่อราคาไปและกลับ ส่วน log return ของการเคลื่อนกลับจะเปลี่ยนเพียงเครื่องหมาย [อ่านเอกสารต้นทาง](https://ssrn.com/abstract=5161959)

ใช้ตัวอย่างสมมติ 80 → 60 → 80 บาท ขาลงคือ −25% แต่ขากลับต้องได้ $80/60-1=33.3333\%$ ส่วน log returns เท่ากับ −0.287682 และ +0.287682 รวมกันเป็นศูนย์

ถ้าขาดทุนเป็นสัดส่วน $L$ ของเงินเริ่มต้น โดย $0\leq L-1$ และเท่ากันเฉพาะที่ศูนย์ จึงไม่ควรแทนสองค่าเข้าหากันโดยไม่ดูขนาดการเปลี่ยนแปลง โดยเฉพาะช่วงตลาดเคลื่อนไหวแรง

## 6. ค่าเฉลี่ย: เดือนเฉลี่ยกับการเติบโตของเงินเป็นคนละคำถาม

**ค่าเฉลี่ยเลขคณิต** ของ simple returns คือ

$$
\bar R=\frac{1}{T}\sum_{t=1}^{T}R_t.
$$

ในตัวอย่าง +20%, −20% ค่าเฉลี่ยเลขคณิตเท่ากับ 0% ต่อเดือน แต่เงินลดลงจริง **ค่าเฉลี่ยเรขาคณิต** ตอบว่า ถ้าโตด้วยอัตราคงที่ทุกเดือน ต้องใช้อัตราเท่าไรจึงได้เงินปลายทางเท่าเดิม

$$
g=\left[\prod_{t=1}^{T}(1+R_t)\right]^{1/T}-1
=\exp(\bar r)-1,
\qquad \bar r=\frac{1}{T}\sum_{t=1}^{T}r_t.
$$

จึงได้ $g=\sqrt{0.96}-1\approx-2.0204\%$ ต่อเดือน และ $1000(1+g)^2=960$ บาท ค่าเฉลี่ยเลขคณิตใช้สรุปผลตอบแทนหนึ่งช่วงจากตัวอย่าง ส่วนค่าเฉลี่ยเรขาคณิตใช้สรุปการเติบโตทบต้นที่เกิดขึ้นแล้ว ทั้งสองไม่ใช่คำรับรองผลตอบแทนในอนาคต

ถ้าวัดเป็นปี ใช้ **CAGR** (compound annual growth rate) โดยให้ $Y$ เป็นจำนวนปีที่ถือ และ $V$ เป็นมูลค่าเงินลงทุนที่ไม่มีฝากถอนภายนอก

$$
\mathrm{CAGR}=\left(\frac{V_T}{V_0}\right)^{1/Y}-1.
$$

เงิน 1,000 → 1,210 บาทในสองปีมี CAGR 10% ต่อปี ไม่ใช่ 21% ÷ 2 = 10.5% และ CAGR ไม่ได้บอกว่าแต่ละปีได้ 10% จริง การทำข้อมูลระยะสั้นให้เป็นอัตราต่อปีเป็นเพียงการแปลงหน่วยด้วยการทบต้น ไม่ใช่การพยากรณ์ว่าจะทำซ้ำได้ทั้งปี

## 7. รวมข้ามสินทรัพย์: กลับมาใช้ simple return

ให้ $w_{i,t-1}$ เป็นน้ำหนักสินทรัพย์ $i$ ตามมูลค่าพอร์ตต้นช่วง โดยน้ำหนักรวมเท่ากับหนึ่ง ถ้าไม่มีฝากถอนหรือซื้อขายระหว่างช่วง และรวมกระแสเงินสดกับค่าใช้จ่ายในผลตอบแทนอย่างสอดคล้องกัน

$$
R_{p,t}=\sum_{i=1}^{N}w_{i,t-1}R_{i,t}.
$$

สมมติพอร์ต 1,000 บาท ลงทุน A 600 บาท และ B 400 บาท ในเดือนเดียวกัน A ได้ +20% ส่วน B ได้ −10%

| สินทรัพย์ | มูลค่าต้นเดือน | ผลตอบแทน | มูลค่าปลายเดือน |
|---|---:|---:|---:|
| A | 600 | +20% | 720 |
| B | 400 | −10% | 360 |
| รวม | 1,000 | **+8%** | **1,080** |

ผลตอบแทนพอร์ตเท่ากับ $0.6(0.20)+0.4(-0.10)=0.08$ ส่วน log return ของพอร์ตต้องคำนวณจาก

$$
r_{p,t}=\ln(1+R_{p,t})
=\ln\left(\sum_i w_{i,t-1}e^{r_{i,t}}\right).
$$

ได้ $\ln(1.08)=0.076961$ แต่การถ่วงน้ำหนัก log return ของสินทรัพย์ตรง ๆ ได้ $0.6\ln(1.2)+0.4\ln(0.9)=0.067249$ ซึ่งไม่เท่ากัน

เมื่อขึ้นเดือนใหม่ น้ำหนัก A กลายเป็น $720/1080=2/3$ และ B เป็น $1/3$ ถ้าไม่ได้ปรับพอร์ต การคงน้ำหนัก 60/40 ในทุกเดือนเท่ากับสมมติว่าปรับพอร์ตกลับสู่น้ำหนักเป้าหมายทุกต้นเดือน ต้องนับต้นทุนการปรับด้วยเมื่อนำไปใช้งานจริง

**ข้ามเวลา:** คูณ gross returns หรือบวก log returns ของพอร์ตเดียวกัน **ข้ามสินทรัพย์ในช่วงเดียวกัน:** ถ่วงน้ำหนัก simple returns ด้วยน้ำหนักต้นช่วง แล้วค่อยแปลงผลรวมเป็น log หากต้องการ

## 8. เปลี่ยนเป็น log ไม่ได้ทำให้ข้อมูลเป็น Normal

Logarithm เป็นการแปลงตัวเลข ไม่ใช่หลักฐานว่าข้อมูลมี [การแจกแจงปกติ](https://nutdnuy.github.io/quantitative-finance-notes/glossary.html#normal-distribution) และการรวมข้ามเวลาได้ด้วยการบวกก็ไม่ได้รับรองความเป็นอิสระของผลตอบแทน

ถ้าตั้งสมมติฐานว่า log returns หลายช่วงมีการแจกแจงปกติร่วมกัน ผลรวมจึงเป็น Normal และเมื่อราคาเริ่มต้นเป็นค่าคงที่บวก ราคาปลายทางที่เขียนเป็น $P_T=P_0e^{\sum_t r_t}$ จะเป็น Lognormal กรณีผลตอบแทนแต่ละช่วงเป็น Normal และเป็นอิสระกันเป็นเงื่อนไขหนึ่งที่เพียงพอ แต่ความเป็นบวกของราคาอย่างเดียวไม่เพียงพอ

บทความของ Simon Leung ชวนพิจารณาข้อจำกัดของสมมติฐานการแจกแจง ในการใช้งานจริงต้องตรวจข้อมูลและวิธีทดสอบเพิ่มเติม การประมาณพารามิเตอร์จากตัวอย่างแล้วใช้ KS test แบบมาตรฐานกับตัวอย่างเดิมต้องปรับวิธีหาค่า p-value ให้รองรับการประมาณนั้น จึงไม่ควรยกค่า p-value ในบทความมาเป็นข้อยืนยันแบบจำลองของเรา [บทความต้นทาง](https://medium.com/@simonleung5jobs/a-brief-overview-on-simple-returns-and-log-returns-in-financial-data-07f2dfbc69ff)

## 9. ทดลองคำนวณและตรวจคำตอบด้วย Python

โค้ดนี้ใช้เฉพาะ Python standard library ใช้ `log1p(R)` คำนวณ $\ln(1+R)$ และ `expm1(r)` คำนวณ $e^r-1$ ซึ่งช่วยลดการสูญเสียความแม่นยำเมื่อค่ามีขนาดเล็ก


In [1]:
import math

prices = [1000.0, 1200.0, 960.0]
simple = [b / a - 1 for a, b in zip(prices, prices[1:])]
logs = [math.log1p(x) for x in simple]
cumulative = math.prod(1 + x for x in simple) - 1
from_logs = math.expm1(math.fsum(logs))
from_endpoints = prices[-1] / prices[0] - 1
assert math.isclose(cumulative, from_endpoints, abs_tol=1e-12)
assert math.isclose(from_logs, from_endpoints, abs_tol=1e-12)

arithmetic = math.fsum(simple) / len(simple)
geometric = math.expm1(math.fsum(logs) / len(logs))
assert math.isclose(prices[0] * (1 + geometric)**2, prices[-1])
print(f"Cumulative: {cumulative:.4%}")
print(f"Arithmetic/month: {arithmetic:.4%}")
print(f"Geometric/month: {geometric:.4%}")

weights = [0.6, 0.4]
asset_returns = [0.2, -0.1]
portfolio_return = math.fsum(w * r for w, r in zip(weights, asset_returns))
terminal_wealth = 600 * 1.2 + 400 * 0.9
assert math.isclose(portfolio_return, terminal_wealth / 1000 - 1)
portfolio_log = math.log1p(portfolio_return)
weighted_log = math.fsum(w * math.log1p(r) for w, r in zip(weights, asset_returns))
assert not math.isclose(portfolio_log, weighted_log)
print(f"Portfolio simple: {portfolio_return:.4%}")
print(f"Portfolio log: {portfolio_log:.6f}; weighted asset logs: {weighted_log:.6f}")


Cumulative: -4.0000%
Arithmetic/month: 0.0000%
Geometric/month: -2.0204%
Portfolio simple: 8.0000%
Portfolio log: 0.076961; weighted asset logs: 0.067249


ผลตอบแทนสะสมต้องได้ −4.0000% ค่าเฉลี่ยเลขคณิต 0.0000% และค่าเฉลี่ยเรขาคณิต −2.0204% ต่อเดือน ส่วนพอร์ตสองสินทรัพย์ได้ simple return 8.0000%

[ดาวน์โหลด Notebook พร้อมเนื้อหาและผลคำนวณ](returns.ipynb) แล้วลองเปลี่ยนเป็นราคา 80 → 60 → 80 ก่อนรันใหม่ สังเกตว่าผลตอบแทนสะสมเป็นศูนย์ แต่ค่าเฉลี่ยเลขคณิตไม่เป็นศูนย์ อย่าป้อนราคาศูนย์หรือติดลบเข้าโค้ดที่ใช้ log นี้

## 10. เลือกใช้ให้ตรงคำถาม

| คำถาม | วิธีคำนวณ |
|---|---|
| ช่วงนี้เงินเพิ่มหรือลดกี่เปอร์เซ็นต์? | Simple total return ที่นับกระแสเงินสดครบ |
| ถือหลายช่วงแล้วเงินโตเท่าไร? | คูณ gross returns แล้วลบหนึ่ง หรือรวม log returns แล้วแปลงกลับ |
| เงินโตเฉลี่ยแบบทบต้นเท่าไร? | Geometric mean หรือ CAGR พร้อมระบุช่วงเวลา |
| พอร์ตหลายสินทรัพย์ได้เท่าไรในช่วงเดียวกัน? | ถ่วงน้ำหนัก simple returns ด้วยน้ำหนักต้นช่วง |
| จะใช้ log returns สร้างแบบจำลองได้ไหม? | ตรวจมูลค่าบวก คุณภาพข้อมูล และสมมติฐานของแบบจำลองก่อน |

กรณีมีฝากถอน เงินเข้าพอร์ตไม่ใช่กำไรจากการลงทุน อัตราเปลี่ยนแปลงของยอดบัญชีจึงใช้ตรง ๆ ไม่ได้ ต้องแยกกระแสเงินสดภายนอกก่อน เช่น แบ่งช่วงตามจุดฝากถอนเพื่อวัด time-weighted return หรือใช้ money-weighted return เมื่อคำถามเกี่ยวกับผลตอบแทนของเงินที่ผู้ลงทุนใส่จริง

ต่อจากบทนี้ อ่าน [Prices and Returns](https://nutdnuy.github.io/quantitative-finance-notes/prices-and-returns.html) เพื่อเตรียมข้อมูลราคา ปันผล และ corporate actions จากนั้นอ่าน [Portfolio Theory](https://nutdnuy.github.io/quantitative-finance-notes/portfolio-theory.html) เพื่อพิจารณาผลตอบแทนร่วมกับความเสี่ยงของพอร์ต

## แหล่งอ้างอิงและข้อสังเกตในการอ่าน

1. Motty Shai. *Simple return vs. Logarithmic return — additional aspects*. 1 กุมภาพันธ์ 2025 ปรับปรุง 2 มีนาคม 2025 ตามไฟล์ PDF ที่ได้รับ — [SSRN 5161959](https://ssrn.com/abstract=5161959). ใช้ประเด็นผลตอบแทนขาไป–ขากลับและการเปลี่ยนผลคูณเป็นผลบวก ไม่รับข้อสรุปว่าการใช้ log เพียงอย่างเดียวทำให้ Backtest ดีขึ้นหรือแก้ความเสี่ยงได้โดยอัตโนมัติ
2. Simon Leung. *A brief overview on simple returns and log returns in financial data*. 5 ธันวาคม 2024 — [Medium](https://medium.com/@simonleung5jobs/a-brief-overview-on-simple-returns-and-log-returns-in-financial-data-07f2dfbc69ff). ใช้เป็นกรอบเปรียบเทียบสองนิยามและข้อควรระวังเรื่องการแจกแจง ตัวอย่างราคา 100 → 110 → 90 → 120 ในต้นทางต้องได้ผลตอบแทนรวม 20% พอดีเมื่อไม่ปัดเศษระหว่างทาง ไม่ใช่ 20.04%
3. AlgoAddict Diary. *Simple Return VS Log Return ความแตกต่างที่ไม่ควรมองข้าม!*. 10 มกราคม 2019 — [Medium](https://medium.com/@info.algoaddict/simple-return-vs-log-return-c075d65f1739). ใช้เป็นจุดเริ่มต้นเรื่องการบวกผลตอบแทนข้ามเวลา สูตรแปลงกลับต้องเป็น $e^r-1$: $e^{\ln(1.5)}=1.5$ คือ gross return จึงต้องลบหนึ่งก่อนรายงานกำไร 50% ไม่จำเป็นต้องใช้ log เสมอไปหากทบต้น simple returns ถูกต้อง

บทเรียนเรียบเรียงใหม่พร้อมตัวอย่างและการตรวจคำนวณของชุด Notes ไม่คัดลอกภาพ ตาราง หรือเผยแพร่ PDF ต้นฉบับ
