const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),axe=require.resolve('axe-core/axe.min.js');
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[],external=[],report={checks:[],states:[]};page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:8763|file:|data:)/.test(r.url()))external.push(r.url());});
 async function scan(name){await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.addScriptTag({path:axe});const result=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.states.push({name,violations:result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});await page.screenshot({path:path.join(__dirname,name+'.png')});}
 await page.goto('http://127.0.0.1:8763/');assert.equal(await page.locator('h1').innerText(),'Welcome');assert.ok(!(await page.locator('body').innerText()).includes('บทที่ 3'));assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.ok(await page.locator('.book-cover').evaluate(i=>i.complete&&i.naturalWidth===1536));await scan('welcome-desktop');report.checks.push('Welcome first; light default; original image loaded; chapter number absent from home');
 await page.getByRole('button',{name:'Search',exact:false}).click();await page.getByRole('searchbox').fill('volatility');await page.waitForFunction(()=>document.querySelectorAll('#search-results a').length>0);assert.ok((await page.locator('#search-results a').count())>1);await scan('welcome-search');await page.keyboard.press('Escape');assert.ok(!(await page.locator('#search-dialog').evaluate(d=>d.open)));
 await page.keyboard.press('Meta+k');assert.ok(await page.locator('#search-dialog').evaluate(d=>d.open));await page.getByRole('searchbox').fill('zzzz-not-a-topic');assert.match(await page.locator('#search-status').innerText(),/ไม่พบ/);await page.getByRole('button',{name:'ปิดการค้นหา',exact:true}).click();report.checks.push('Search title/body, keyboard shortcut, Escape, close and no-result state');
 await page.getByRole('link',{name:'เปิดบทเรียน →',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.lab').length===12);assert.equal(await page.locator('h1').innerText(),'พฤติกรรมแบบสุ่มของสินทรัพย์');assert.equal(await page.locator('.katex').count(),28);await scan('book-lesson-desktop');
 const slider=page.locator('#returns-lab input');await slider.focus();await slider.press('End');assert.match(await page.locator('#returns-lab .calculation-strip').innerText(),/2.208%/);
 await page.locator('details.extension summary').click();await page.getByRole('button',{name:'บันทึกชุดทดลอง',exact:true}).click();assert.equal(await page.locator('.saved-list button').count(),1);await page.getByRole('button',{name:'ขั้นที่ 2',exact:true}).click();assert.match(await page.locator('.step-body').innerText(),/2%/);report.checks.push('12 labs and 28 equations after spreadsheet exercise removal; source-price selection, saved GBM and guided exercise work');
 await page.goto('http://127.0.0.1:8763/');await page.locator('#theme-button').click();await scan('welcome-dark');
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8763/');await scan('welcome-mobile');assert.ok(await page.locator('.mobile-cover').isVisible());await page.getByRole('button',{name:'สารบัญ',exact:true}).click();assert.equal(await page.locator('#menu-button').getAttribute('aria-expanded'),'true');await page.getByRole('button',{name:'Search',exact:false}).click();await page.getByRole('searchbox').fill('Jensen');await scan('welcome-search-mobile');await page.keyboard.press('Escape');
 await page.goto('http://127.0.0.1:8763/random-assets.html');await page.waitForFunction(()=>document.querySelectorAll('.lab').length===12);await scan('book-lesson-mobile');await page.emulateMedia({reducedMotion:'reduce'});await page.locator('details.extension summary').click();await page.getByRole('button',{name:'บันทึกชุดทดลอง',exact:true}).click();assert.equal(await page.locator('.saved-list button').count(),1);report.checks.push('Mobile cover, menu, search, lesson and reduced-motion saved list work');
 await page.goto('file://'+path.join(root,'index.html'));assert.equal(await page.locator('h1').innerText(),'Welcome');await page.getByRole('button',{name:'สารบัญ',exact:true}).click();await page.getByRole('button',{name:'Search',exact:false}).click();await page.getByRole('searchbox').fill('Wiener');assert.ok((await page.locator('#search-results a').count())>0);report.checks.push('Offline file opening and search work without network');
 const version=await (await fetch('http://127.0.0.1:8763/__version')).text();const css=path.join(root,'book.css');const marker='\n/* preview-watch-check */\n';fs.appendFileSync(css,marker);
 let changed=false;for(let i=0;i<25;i++){await new Promise(r=>setTimeout(r,200));if(await (await fetch('http://127.0.0.1:8763/__version')).text()!==version){changed=true;break;}}
 fs.writeFileSync(css,fs.readFileSync(css,'utf8').replace(marker,''));assert.ok(changed);report.checks.push('Saving a source CSS file triggers a successful rebuild and version update');
 report.errors=errors;report.external=external;assert.deepEqual(errors,[]);assert.deepEqual(external,[]);report.status=report.states.every(s=>s.violations.length===0)?'passed':'needs-fix';fs.writeFileSync(path.join(__dirname,'welcome-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
